DemoDay/urls.py
"""
Definition of urls for DemoDay.
"""

from datetime import datetime
from django.conf.urls import patterns, url

# Uncomment the next lines to enable the admin:
from django.conf.urls import include
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'app.views.home', name='home'),
    url(r'^thank-you/$', 'app.views.thanks', name='thanks'),
   
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^grappelli/', include('grappelli.urls')), 
    url(r'^admin/', include(admin.site.urls)),
)

app/models.py
"""
Definition of models.
"""

from django.db import models

class Startup(models.Model):
    name = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    desc = models.TextField(max_length=1024, null=True)
    twitter = models.CharField(max_length=200, null=True)
    logo = models.CharField(max_length=200, null=True )
    link = models.CharField(max_length=200, null=True)

    def __str__(self):              
        return self.name

class Founder(models.Model):
    startup = models.ForeignKey(Startup)
    name = models.CharField(max_length=200)
    title = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)
    linkedin = models.CharField(max_length=200, null=True)
    headshot = models.CharField(max_length=200, null=True)
    twitter = models.CharField(max_length=200, null=True)

    def __str__(self):              
        return self.name

app/forms.py
"""
Definition of forms.
"""

from django import forms


class InvestorForm(forms.Form):
    investor_name = forms.CharField(label='Name')
    investor_org = forms.CharField(label='Organization')
    investor_email = forms.EmailField(label='Email')
    investor_companies = forms.CharField()


app/views.py
"""
Definition of views.
"""

from django.shortcuts import render
from django.http import HttpRequest
from django.template import RequestContext
from datetime import datetime

from .models import Startup, Founder
from .forms import InvestorForm
from django.http.response import HttpResponseRedirect
import re
import sendgrid

def home(request):
    """Renders the home page."""
    assert isinstance(request, HttpRequest)

    startup_list = Startup.objects.all()

    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = InvestorForm(request.POST)

        # check whether it's valid:
        if form.is_valid():

            companies = re.split(', ', form.cleaned_data['investor_companies'])

            for company in companies:

                client = sendgrid.SendGridClient("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")
                message = sendgrid.Mail()

                message.add_to("tereza.nemessanyi@microsoft.com")
                message.add_bcc("ryanjoy@microsoft.com")
                message.set_from("tereza.nemessanyi@microsoft.com")
                message.set_subject("[NRF Startup Showcase 2016] {0} is interested in {1}".format(form.cleaned_data['investor_org'], company))
            

                html_fragment = '<html><body>Hello,<br />{0} ({1}) at {2} is interested in {3}<br /></body></html>'
            
                message.set_html(html_fragment.format(form.cleaned_data['investor_name'], form.cleaned_data['investor_email'], form.cleaned_data['investor_org'], company))

                client.send(message)
            
            # redirect to a new URL:
            return HttpResponseRedirect('/thank-you')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = InvestorForm()


    return render(
        request,
        'app/index.html',
        context_instance = RequestContext(request,
        {
            'title':'Healthcare Startup Showcase 2016',
            'startup_list' : startup_list,
            'form' : form,
            'year':datetime.now().year,
        })
    )

def thanks(request):
    """Renders the thank you page."""
    assert isinstance(request, HttpRequest)

    return render(
        request,
        'app/thanks.html',
        context_instance = RequestContext(request,
        {
            'title':'NRF Startup Showcase 2016',
            'year':datetime.now().year,
        })
    )

app/templates/app/index.html
{% extends "app/layout.html" %}

{% block content %}

{% if startup_list %}
<script>
    var companies = [
{% for startup in startup_list %}        
        {
        name: '{{ startup.name }}',
        desc: '{{ startup.desc }}',
        logo: '{{ startup.logo }}',
        link: '{{ startup.link }}',
        email: '{{ startup.email }}',
        founders: [
  {% for founder in startup.founder_set.all %} 
    
        {
            name: '{{ founder.name}}',
            title: '{{ founder.title}}',
            image: '{{ founder.headshot}}'
        },
   {% endfor %} 
        
        ]
    },

 {% endfor %}    
];
</script>
        {% else %}

        {% endif %}


  <nav class="navbar navbar-default" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <div class="mslogo-container">
            <a href="http://www.microsoft.com/" ><img alt="Microsoft" src="https://assets.onestore.ms/cdnfiles/onestorerolling-1512-09001/shell/v3/images/logo/microsoft.png"></a>
        </div>
    </div>
  </nav>

  <nav data-nav-status="toggle" class="navigation-bar is-hidden navbar navbar-default navbar-interest" role="navigation">
    <div class="navbar-header">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <div class="row">
            <div class="col-md-6 col-xs-7 navbar-counter">
              <p id="counter" class="counter"></p>
            </div>
            <div class="col-md-6 col-xs-5 navbar-button">
              <button data-toggle="modal" data-target="#interest-modal" class="btn btn-default">Next <i class="fa fa-caret-right"></i></button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </nav>

  <div class="featurette fluid-container">
    <div class="wrapper row">

      <div id="connect-apps" class="container">

        <header>
          <h1>{{ title }}</h1>
          <p>Welcome! Please click the buttons below to express interest in one or more startups you met today.</p>
        </header>
        <div id="companies" class="row">
        </div>

        <footer>
          <p>&copy; 2015 Microsoft</p>
        </footer>
      </div>
    </div>
  </div>

  <div id="interest-modal" class="modal fade">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title">Thank you for your interest!</h4>
        </div>
        <div class="modal-body">
          <p>You've selected: <span id="modal-companies"></span></p>
          <p>Please let us know how they can reach you: </p>
        
        <form action="." method="post">
            
                <input name="investor_name" id="id_investor_name" type="text" placeholder="Your name">
                <input name="investor_email" id="id_investor_email" type="email" placeholder="Your email">
                <input name="investor_org" id="id_investor_org" type="text" placeholder="Your organization">

                <input name="investor_companies" id="id_investor_companies" type="hidden">

            <input type="submit" value="Submit">
        </form>

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->

  <div id="thankyou-modal" class="modal fade">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title">Thank you for reaching out!</h4>
        </div>
        <div class="modal-body">
          <p>Awesome, thank you! Your contact info will be passed over to CEOs.
           Also feel free to contact <a href="mailto:">@microsoft.com</a> for additional info.</p>
         </div>
         <div class="modal-footer">
         <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->



{% endblock %}

app/templates/app/layout.html
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title>{{ title }}</title>
  <meta name="description" content="{{ title }}">
    {% load staticfiles %}
  <link href="//acom.azurecomcdn.net/80C57D/cdn/cvt-90cdaf487716184e4034000935c605d1633926d348116d198f355a98b8c6cd21/images/icon/favicon.ico" rel="icon" type="image/x-icon">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <link href="{% static 'app/stylesheets/site.css' %}" rel="stylesheet">
</head>

<body data-spy="scroll" data-target=".navbar-fixed-top">
    
{% block content %}{% endblock %}

    <script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    <script src="{% static 'app/scripts/respond.js' %}"></script>
    <script src="{% static 'app/scripts/icheck.min.js' %}"></script>
    <script src="{% static 'app/scripts/main.js' %}"></script>
{% block scripts %}{% endblock %}

</body>
</html>

app/templates/app/thanks.html
{% extends "app/layout.html" %}

{% block content %}



  <nav class="navbar navbar-default" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <div class="mslogo-container">
            <a href="http://www.microsoft.com/" ><img alt="Microsoft" src="https://assets.onestore.ms/cdnfiles/onestorerolling-1512-09001/shell/v3/images/logo/microsoft.png"></a>
        </div>
    </div>
  </nav>

  <div class="featurette fluid-container">
    <div class="wrapper row">

      <div id="connect-apps" class="container">

        <header>
          <h1>Thank you!</h1>
            <p>We're delighted you want to connect with our startups. Your request is being directly forwarded to the startup. Expect to hear from them very shortly.</p>
            <p>Questions or comments? We're happy to help.<br />
               Please contact <a href="mailto:">tereza.nemessanyi@microsoft.com</a>.</p>        
        </header>
        


        <footer>
          <p>&copy; 2015 Microsoft</p>
        </footer>
      </div>
    </div>
  </div>

 

{% endblock %}